// Arabic fallback copy; every string can be overridden in site_content.
export const ar = {
  brand: { name: 'نور', tagline: 'للتشخيص الطبي' },
  seo: { title: 'نور للتشخيص الطبي — التصوير والتحاليل والفحوص المتخصصة', description: 'مركز نور للتشخيص الطبي يجمع التصوير الطبي والتحاليل والفحوص المتخصصة. أرسلوا طلب موعد بسهولة عبر الموقع.' },
  nav: { services: 'الخدمات', about: 'من نحن', team: 'الفريق الطبي', faq: 'الأسئلة الشائعة', contact: 'اتصل بنا', cta: 'احجز موعدًا', openMenu: 'افتح القائمة' },
  hero: { eyebrow: 'مركز التشخيص الطبي', lines: ['التصوير الطبي', 'التحاليل الطبية', 'الفحوص المتخصصة'], cta: 'احجز موعدًا', ctaSecondary: 'واتساب' },
  services: { title: 'خدماتنا', intro: 'ثلاثة تخصصات تشخيصية في مركز واحد.', cta: 'اكتشف المزيد', categories: { imagerie: 'التصوير الطبي', laboratoire: 'مختبر التحاليل الطبية', examens: 'الفحوص المتخصصة' } },
  whyNour: { title: 'لماذا نور', eyebrow: 'لماذا نحن', points: [
    { title: 'الخبرة', text: 'فريق مؤهل يتمتع بخبرة واسعة.' },
    { title: 'الرعاية', text: 'استقبال واهتمام في كل مرحلة.' },
    { title: 'التشخيص', text: 'تجهيزات موثوقة ونتائج دقيقة.' },
    { title: 'القرب', text: 'مركز يسهل الوصول إليه ويصغي لاحتياجاتكم.' },
  ] },
  departments: { title: 'أقسامنا', intro: 'تعرّف على أقسام مركز نور الطبي.' },
  about: { title: 'عن مركز نور', eyebrow: 'من نحن' },
  team: { title: 'فريقنا الطبي', intro: 'مختصون يرافقونكم في رحلة التشخيص.' },
  patientInfo: { title: 'معلومات للمرضى', intro: 'ما تحتاجون إلى معرفته قبل زيارتكم.', categories: { preparation: 'التحضير', documents: 'الوثائق', jeune: 'الصيام', consignes: 'إرشادات' } },
  howItWorks: { title: 'كيف تتم الزيارة', steps: [
    { number: '01', title: 'الطلب', text: 'تقدّمون طلب الموعد عبر الموقع.' },
    { number: '02', title: 'التأكيد', text: 'يؤكد فريقنا الموعد المتاح.' },
    { number: '03', title: 'الحضور', text: 'تصلون في الموعد المحدد.' },
    { number: '04', title: 'الفحص', text: 'يُجرى الفحص أو التحليل المطلوب.' },
  ] },
  testimonials: { title: 'آراء مرضانا' },
  faq: { title: 'الأسئلة الشائعة' },
  reservation: {
    title: 'احجز موعدًا',
    intro: 'هذه الاستمارة مخصصة لطلبات المواعيد والإجراءات الإدارية. لا تستخدمها في الحالات الطبية الطارئة.',
    fields: { fullName: 'الاسم الكامل', phone: 'رقم الهاتف', service: 'الخدمة', preferredDate: 'التاريخ المرغوب', preferredTime: 'الوقت المرغوب', document: 'وثيقة أو صورة (اختياري)', message: 'رسالة (اختياري)' },
    submit: 'إرسال الطلب', submitting: 'جارٍ الإرسال…', selectService: 'اختر خدمة…',
    cooldown: 'يرجى الانتظار قبل إرسال طلب جديد.', security: 'يرجى إكمال التحقق الأمني.',
    error: 'حدث خطأ. يرجى المحاولة مجددًا.', whatsappMessage: 'مرحبًا، أود تأكيد طلب موعد باسم',
    validation: {
      fullNameRequired: 'الاسم الكامل مطلوب.', fullNameLength: 'يجب أن يتراوح الاسم بين حرفين و80 حرفًا.',
      phoneRequired: 'رقم الهاتف مطلوب.', phoneInvalid: 'رقم الهاتف غير صالح.',
      serviceRequired: 'يرجى اختيار خدمة.', dateRequired: 'يرجى اختيار تاريخ.',
      dateFuture: 'يرجى اختيار تاريخ قادم.', timeRequired: 'يرجى اختيار وقت.',
      messageLength: 'الرسالة محدودة بـ500 حرف.',
    },
    upload: { checking: 'جارٍ التحقق…', add: 'إضافة وثيقة أو صورة', hint: 'JPG أو PNG أو WEBP أو PDF — بحد أقصى 8 ميغابايت', remove: 'إزالة الملف',
      errors: { missing: 'لم يتم اختيار ملف.', size: 'يتجاوز الملف الحجم الأقصى البالغ 8 ميغابايت.', type: 'صيغة غير مدعومة. الصيغ المقبولة: JPG وPNG وWEBP وPDF.', signature: 'محتوى الملف لا يطابق صيغته.', read: 'تعذرت قراءة الملف.' } },
    success: { title: 'تم إرسال الطلب', text: 'تم تسجيل طلبكم. سيتصل بكم فريقنا لتأكيد الموعد.', whatsapp: 'التأكيد أيضًا عبر واتساب' },
  },
  contact: { title: 'اتصل بنا', address: 'العنوان', phone: 'الهاتف', hours: 'ساعات العمل', directions: 'الاتجاهات' },
  footer: { rights: 'جميع الحقوق محفوظة.', links: 'روابط' },
  common: {
    open: 'مفتوح', closed: 'مغلق', loading: 'جارٍ التحميل…',
    emptyServices: 'لا توجد خدمات حاليًا.', emptyTestimonials: 'لا توجد شهادات حاليًا.',
    emptyFaq: 'لا توجد أسئلة حاليًا.', emptyTeam: 'لا يوجد أعضاء للعرض حاليًا.',
    emptyPatientInfo: 'لا توجد معلومات حاليًا.', serviceNotFound: 'الخدمة غير موجودة.',
    backToServices: 'العودة إلى الخدمات', allServices: 'جميع الخدمات',
    appointmentRequired: 'يتطلب موعدًا', preparation: 'التحضير',
    pageNotFound: 'الصفحة غير موجودة', backHome: 'العودة إلى الرئيسية', close: 'إغلاق',
    turnstileDisabled: 'التحقق الآلي معطل في بيئة التطوير.',
  },
}
