// French fallback copy. Database site_content may override string leaves.
export const fr = {
  brand: {
    name: 'NOUR',
    tagline: 'Diagnostic Medical',
  },
  seo: {
    title: 'NOUR Diagnostic Medical — Imagerie, Laboratoire, Examens spécialisés',
    description: "NOUR Diagnostic Medical : imagerie médicale, laboratoire d'analyses médicales et examens spécialisés. Prenez rendez-vous en ligne simplement et en toute confiance.",
  },
  nav: {
    services: 'Services',
    about: 'À propos',
    team: 'Équipe',
    faq: 'FAQ',
    contact: 'Contact',
    cta: 'Prendre rendez-vous',
    openMenu: 'Ouvrir le menu',
  },
  hero: {
    eyebrow: 'Centre de diagnostic médical',
    lines: ['Imagerie médicale', 'Analyses médicales', 'Examens spécialisés'],
    cta: 'Prendre rendez-vous',
    ctaSecondary: 'WhatsApp',
  },
  services: {
    title: 'Nos services',
    intro: 'Trois pôles de diagnostic, réunis en un seul centre.',
    cta: 'Découvrir',
    categories: {
      imagerie: "Imagerie médicale",
      laboratoire: "Laboratoire d'analyses médicales",
      examens: 'Examens spécialisés',
    },
  },
  whyNour: {
    title: 'Pourquoi NOUR',
    eyebrow: 'Pourquoi nous',
    points: [
      { title: 'Expertise', text: 'Une équipe qualifiée et expérimentée.' },
      { title: 'Prise en charge', text: 'Un accueil attentif à chaque étape.' },
      { title: 'Diagnostic', text: 'Des équipements fiables et précis.' },
      { title: 'Proximité', text: 'Un centre accessible et à l’écoute.' },
    ],
  },
  departments: {
    title: 'Nos départements',
    intro: 'La structure médicale de NOUR, en un coup d’œil.',
  },
  about: {
    title: 'À propos de NOUR',
    eyebrow: 'À propos',
  },
  team: {
    title: 'Notre équipe médicale',
    intro: 'Des praticiens dédiés à votre diagnostic.',
  },
  patientInfo: {
    title: 'Informations patients',
    intro: 'Ce qu’il faut savoir avant votre venue.',
    categories: {
      preparation: 'Préparation',
      documents: 'Documents',
      jeune: 'Jeûne',
      consignes: 'Consignes',
    },
  },
  howItWorks: {
    title: 'Comment ça marche',
    steps: [
      { number: '01', title: 'Demande', text: 'Vous soumettez votre demande de rendez-vous.' },
      { number: '02', title: 'Confirmation', text: 'Notre équipe confirme la disponibilité.' },
      { number: '03', title: 'Rendez-vous', text: 'Vous vous présentez à l’heure convenue.' },
      { number: '04', title: 'Consultation', text: 'Votre examen ou analyse est réalisé.' },
    ],
  },
  testimonials: {
    title: 'Ce qu’en disent nos patients',
  },
  faq: {
    title: 'Questions fréquentes',
  },
  reservation: {
    title: 'Prendre rendez-vous',
    intro:
      'Ce formulaire est destiné aux demandes de rendez-vous et démarches administratives. Il ne doit pas être utilisé en cas d’urgence médicale.',
    fields: {
      fullName: 'Nom complet',
      phone: 'Téléphone',
      service: 'Service',
      preferredDate: 'Date souhaitée',
      preferredTime: 'Horaire souhaité',
      document: 'Document / image (optionnel)',
      message: 'Message (optionnel)',
    },
    submit: 'Envoyer la demande',
    submitting: 'Envoi en cours…',
    selectService: 'Sélectionner…',
    cooldown: 'Veuillez patienter avant de soumettre une nouvelle demande.',
    security: 'Veuillez compléter la vérification de sécurité.',
    error: 'Une erreur est survenue. Veuillez réessayer.',
    whatsappMessage: 'Bonjour, je souhaite confirmer ma demande de rendez-vous',
    validation: {
      fullNameRequired: 'Le nom complet est requis.',
      fullNameLength: 'Le nom doit contenir entre 2 et 80 caractères.',
      phoneRequired: 'Le numéro de téléphone est requis.',
      phoneInvalid: 'Numéro de téléphone invalide.',
      serviceRequired: 'Veuillez sélectionner un service.',
      dateRequired: 'Veuillez choisir une date.',
      dateFuture: 'La date doit être future.',
      timeRequired: 'Veuillez choisir un horaire.',
      messageLength: 'Le message est limité à 500 caractères.',
    },
    upload: {
      checking: 'Vérification…',
      add: 'Ajouter un document ou une image',
      hint: 'JPG, PNG, WEBP ou PDF — 8 Mo max',
      remove: 'Retirer le fichier',
      errors: { missing: 'Aucun fichier sélectionné.', size: 'Le fichier dépasse la taille maximale de 8 Mo.', type: 'Format non supporté. Formats acceptés : JPG, PNG, WEBP, PDF.', signature: 'Le contenu du fichier ne correspond pas à son format.', read: 'Impossible de lire le fichier.' },
    },
    success: {
      title: 'Demande envoyée',
      text: 'Votre demande a bien été enregistrée. Notre équipe vous contactera pour la confirmer.',
      whatsapp: 'Confirmer aussi par WhatsApp',
    },
  },
  contact: {
    title: 'Nous contacter',
    address: 'Adresse',
    phone: 'Téléphone',
    hours: 'Horaires',
    directions: 'Itinéraire',
  },
  footer: {
    rights: 'Tous droits réservés.',
    links: 'Liens',
  },
  common: {
    open: 'Ouvert',
    closed: 'Fermé',
    loading: 'Chargement…',
    emptyServices: 'Aucun service pour le moment.',
    emptyTestimonials: 'Aucun témoignage pour le moment.',
    emptyFaq: 'Aucune question pour le moment.',
    emptyTeam: 'Aucun membre à afficher pour le moment.',
    emptyPatientInfo: 'Aucune information pour le moment.',
    serviceNotFound: 'Service introuvable.',
    backToServices: 'Retour aux services',
    allServices: 'Tous les services',
    appointmentRequired: 'Rendez-vous requis',
    preparation: 'Préparation',
    pageNotFound: 'Page introuvable',
    backHome: 'Retour à l’accueil',
    close: 'Fermer',
    turnstileDisabled: 'Vérification anti-robot désactivée en développement.',
  },
}
